### ISSUE TITLE
[BS] two (or more?) Points per place?

### ISSUE THREAD

**Issue by sennierer** [InTaVia/source-dataset-conversion#30]
Found that when debugging some wilde running queries:

```
<http://www.intavia.eu/bs/spaceprimitive/14657> a crm:E94_Space_Primitive ;

      crm:P168_place_is_defined_by "Point ( +28.7572 +60.714 )"^^geo:wktLiteral,

      "Point ( +9.39635 +56.452 )"^^geo:wktLiteral
```

These points are rather far away from each other. Is this due to automatic linking? And if yes, could/should we try to add metadata to these data so we know how it was produced?

**Comment by johannesliem** [comment]
Currently, when querying the backend on the BS data, for several examples multiple events with the same ID but slightly different geocoordinates (same place ID though!) are returned.
 
Example query: https://intavia-backend.acdh-dev.oeaw.ac.at/api/entities/search?page=1&limit=50&q=Hautam%C3%A4ki&datasets=http%3A%2F%2Fldf.fi%2Fnbf%2Fdata&includeEvents=true

see events: http://www.intavia.eu/bs/birthevent/2879, http://www.intavia.eu/bs/event/2879-12, http://www.intavia.eu/bs/birthevent/1380, http://www.intavia.eu/bs/deathevent/1380

Similar for events (same ID) but different startDates and endDates. example query: https://intavia-backend.acdh-dev.oeaw.ac.at/api/entities/search?page=1&limit=50&q=Minna&datasets=http%3A%2F%2Fldf.fi%2Fnbf%2Fdata&includeEvents=true

for date fields see events: http://www.intavia.eu/bs/event/2745-4
for places see (different place IDs!): http://www.intavia.eu/bs/event/2745-2

The frontend is going to query entities ad events by id, which makes unique ids for entities and events important.

**Comment by ptleskin** [comment]
Is the BS data at the endpoint up to date.
There's the latest update https://github.com/InTaVia/source-dataset-conversion/blob/main/BS_dataset/bs2intavia.ttl in which this issue should be solved

**Comment by yoge1** [comment]
I don't think we currently have in place a Prefect flow updating the changes in GitHub repo's ttl files to the triplestore. In the meantime, I now udated the BS data https://github.com/InTaVia/source-dataset-conversion/blob/main/BS_dataset/bs2intavia.ttl into the triplestore (named graph http://ldf.fi/nbf/data). However, I still see for an individual space primitive multiple triples in the form
`?spaceprimitive crm:P168_place_is_defined_by "LAT#LON"^^<http://www.bigdata.com/rdf/geospatial/literals/v1#lat-lon>`
which are in the named graph http://www.intavia.eu/test/geo_v1. @sennierer are these used by the API / how should these be updated?
